spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/hdr_rest_server?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: 12345
  thymeleaf: # Thymeleaf
      cache: false
      mode: HTML
      encoding: UTF-8
      prefix: file:src/main/resources/templates/
      resources: # Static resources
        static-locations: file:src/main/resources/static
        cache:
          period: 0
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

server:
 port: 8081





