spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/Healthy_desserts_recipes?createDatabaseIfNotExist=true&useSSL=false"
    username: "root"
    password: "12345"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  sql:
    init:
      mode: never

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    org:
      hibernate:
        SQL: WARN
        type:
          descriptor: TRACE

cloud:
  service:
    mocked: false

    whether:
      api-key: "30bbc14329b65a2e4a74dc84dc4a4765"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail}
    password: ${password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        api:
          to: ${business-mail}