spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/Healthy_desserts_recipes?createDatabaseIfNotExist=true&useSSL=false"
    username: "root"
    password: "12345"
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    defer-datasource-initialization: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true
        message:
          api:
            baseUrl: "http://localhost:8081"

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    org:
      hibernate:
        SQL: WARN
        type:
          descriptor: TRACE

cloud:
  service:
    mocked: false

    whether:
      api-key: ${whether.api-key}


mail:
        host: smtp.gmail.com
        port: 587
        username: "${email_username}"
        password: "${password_email}"


message:
  api:
    baseUrl: "http://localhost:8081"

    security.enable-csrf: false

